### ISSUE TITLE
HTML page links need update in the README

### ISSUE THREAD

**Issue by durack1** [PCMDI/input4MIPs_CVs#107]
The previous path

```
https://pcmdi.github.io/input4MIPs_CVs/docs/input4MIPs_files_CMIP6Plus.html
```
has been augmented with an additional subdir
```
https://pcmdi.github.io/input4MIPs_CVs/docs/database-views/input4MIPs_files_CMIP6Plus.html
```

**Comment by znichollscr** [comment]
Oops.

The link underneath "For different, pre-prepared views of the database, see [database views](https://github.com/PCMDI/input4MIPs_CVs/blob/main/database-views)" is also broken.

The CR logo also doesn't render correctly.

I'll hot fix now.
