### ISSUE TITLE
Biomass burning data publication

### ISSUE THREAD

**Issue by znichollscr** [PCMDI/input4MIPs_CVs#128]
Issue for tracking publication of the biomass burning data

**Comment by znichollscr** [comment]
Some issues we hit during this process:

- "license" vs. "licence" catching us out (need american spelling for this attribute, not british)
- mismatch between filename and variable in the file (filename has to match variable_id, which should match the variable name for single variable files)
- using "fx" for fixed files, rather than another frequency value
- file upload with ~300 big files was fun and games via FTP, seemed to behave in the end

**Comment by durack1** [comment]
Ok we have 298 files down, and now processed and ready for publication tomorrow.

@znichollscr take a peek at `../durack1/input4MIPs` where all 298 files have been copied across into the associated DRS

**Comment by znichollscr** [comment]
Alrighty:

- all the files still have "licence" rather than "license"
- most of the files aren't named correctly. The variable_id in the file's attributes doesn't match the filename (e.g. `C2H5OH-percentageDEFO_input4MIPs_emissions_CMIP_DRES-CMIP-BB4CMIP7-1-0_gn_175001-202212.nc` has `variable_id = "percentage_DEFO"`). Most of the emissions files (e.g. CO2, BC, CH4) seem to be ok.
- gridcellarea
    - gridcellarea isn't a valid standard name (surprisingly), so we need to delete the "standard_name" attribute from the gridcellarea variable and set the "long_name" attribute to "gridcellarea" instead
