### ISSUE TITLE
Clarifying rules around controlled vocabularies

### ISSUE THREAD

**Issue by znichollscr** [PCMDI/input4MIPs_CVs#15]
In short, it's not clear to me what the rules for the controlled vocabularies are. For example, which fields are compulsory, which can be inferred from data, which are only required for ESGF (i.e. are things that data providers shouldn't worry about, but tooling after submission does need to handle).

To get the conversation started, I've made a google doc here: https://docs.google.com/document/d/1oLK4mWW6TX2YPrhGoLdMLcrK7vX1flU3BjiheTb2Hwk/edit?usp=sharing

Once we've got something a bit more concrete, I will pull everything back into issues that we can track across the various repositories.

**Comment by znichollscr** [comment]
@durack1 your thoughts on the google doc above would be great. Is it also worth getting Karl's thoughts? (I assume we should bring Vaishali in too, but I was going to wait until we had more model specific questions before doing that)

cc @lewisjared

**Comment by durack1** [comment]
@znichollscr I've been making some progress on templates and updating this with real info at https://github.com/PCMDI/input4MIPs_CVs/blob/main/input4MIPs_source_id.json - more than happy to touch base about this, this week if possible, so we can get this finalized and start getting data prepared and published

@vnaik60 also happy for you to chime in on this

**Comment by znichollscr** [comment]
Cool, looks good. I'll message you via email about touching base

**Comment by znichollscr** [comment]
Notes from reading #24:

- the following bits of metadata can vary by file (imagine a group that provides variables in different categories, for example), so I would suggest removing them from the source_id registration: "dataset_category", "datetime_start", "datetime_stop", "frequency", "grid_label", "nominal_resolution", "realm"

**Comment by durack1** [comment]
Good catch. The dataset_category is a bit of a tricky one, but for the most part all contributed data loosely fits one of the existing bins
https://github.com/PCMDI/input4MIPs_CVs/blob/1834918ffa975cc692a7a1f5fa93954f16d499c0/input4MIPs_dataset_category.json#L1-L14
For datetime*, I have populated the first and last entries when I could update them - so this of this more like the maximum temporal range, with the end the most point of the values (but the start also important, think a historical dataset that starts in 1900, you'd not be able to use it for the 1850-1899 standard period, extending to 2022). Frequency is most often multiple, grid_label is normally a single grid, but not always - your data, nominal_resolution is meant to be a representative, related to grid and realm is another that could be multiple. This is what it looks like in practice (and I have realized that the frequency needs to be updated, it's another multiple)
https://github.com/PCMDI/input4MIPs_CVs/blob/1834918ffa975cc692a7a1f5fa93954f16d499c0/input4MIPs_source_id.json#L3528-L3594

**Comment by znichollscr** [comment]
Yep I see all of that. My suggestion is probably more direct:

Given that these keys are file specific, I would suggest removing them from the source ID registration. They apply to individual files, not all files supplied by a specific source.

**Comment by durack1** [comment]
The keys are specific, BUT, if I am searching for data to meet my needs, some of this information needs to be available. I agree with the general sentiment, but it would reduce the source_id registration mostly to an identity, contact, institution etc, without keeping the information that is relevant for data searching and use

**Comment by znichollscr** [comment]
That's ok, no? You can still get the data relevant for data searching and use, you just have to get it from the data. That makes sense, get information about the data from the data, not from the source ID (where the information about the data can be either a) wrong or b) ambiguous).

If the purpose of source ID is to be a container about everything held in a data file, then it needs to be renamed and repurposed no? It should be called, "data information" or something and there should be an entry for every single file.

The workflow I'm proposing would be something like:

1. register source ID (identity, contact, institution etc)
2. data provider creates data
3. validate the data
4. once data has passed validation, we can auto-create all the other information by just reading the files. This gives us all the stuff we want for searching on a file by file basis e.g. frequency, realm etc.
5. use this information to create whatever is needed for ESGF search etc.

**Comment by durack1** [comment]
@znichollscr this seems to also be redundant with the ongoing progress, so will close
