### ISSUE TITLE
anthropogenic emissions tweak - targeting CEDS-CMIP-2025-11-25

### ISSUE THREAD

**Issue by durack1** [PCMDI/input4MIPs_CVs#154]
@hahsan1 @ssmithClimate, the latest CEDS-CMIP-2024-10-21 data checks out ok, so I've pulled that across into the publication queue. If the supplemental data is available before Monday, I'll try and pull it all down together and get these published in one hit.

Issues to solve:
- [x] Missing `license` global attribute
- [x] Missing `source_version` global attribute (rename dataset_version_number)
- [x] Missing `areacella` variable (grid cell area)
- [x] Missing solid biofuel emissions
- [ ] Update mip_era = CMIP7 (when final version is ready for CMIP7 DECK commencement)

Generate CEDS-PROV-CMIP-2025-XX-YY to catch 202201 to near-present data, CEDS-CMIP-2025-XX-YY for 185001-202112 data

**Comment by znichollscr** [comment]
Thanks Paul, a couple of things to double check:

> Missing license global attribute

Ideally we would get a "license" attribute with full text and a "license_id" attribute with value "CC BY 4.0"

> Update mip_era = CMIP7

We want the mip_era to stay "CMIP6Plus" until the version that is ready for the fast track no?

> Generate CEDS-PROV-CMIP-2025-XX-YY to catch 202201 to near-present data, CEDS-CMIP-2025-XX-YY for 185001-202112 data

Is this really how we want to do this? For every data set, have a different source ID for 1850 to 2021 data and a different source ID for 2022 onwards? Maybe mangling everything into the source ID is the only way in the current set up (x-ref #64).

**Comment by durack1** [comment]
> We want the mip_era to stay "CMIP6Plus" until the version that is ready for the fast track no?

100%. If there are tweak updates as issues are identified, and there is the appetite to fix and release a new (sub)set of files, that would be my preference, and we iterate, iterate. Once the stream of issues slows to near-zero, then we'd be ready to mint the "final" CMIP7 versions and toggle across the `mip_era` identifier

**Comment by znichollscr** [comment]
@durack1 given we've merged #161, should we close and deal with the switch to MIP era equal to "CMIP7" in a separate set of issues?

**Comment by durack1** [comment]
Sounds good to me, but we do need to update the docs (particularly [input4MIPs_delivery-summary_CMIP6Plus.html](https://input4mips-controlled-vocabularies-cvs.readthedocs.io/en/latest/database-views/input4MIPs_delivery-summary_CMIP6Plus.html)) to make sure Steve's two source_id's CEDS-CMIP-2024-10-21* and CEDS-CMIP-2024-11-25*, not sure how you want to deal with that..

**Comment by znichollscr** [comment]
Ooops, good pick up, see #167
