### ISSUE TITLE
Catch up on releases

### ISSUE THREAD

**Issue by durack1** [PCMDI/input4MIPs_CVs#163]
I've just realized we've been great at publishing new data, but not tagging new releases.. Which will mean our comms aren't as tight as we'd like to be.. We might have to tag a couple of releases to delineate the CEDS-CMIP-2024-10-21 release along with the updates thereafter

**Comment by znichollscr** [comment]
I'm not sure where using the releases in our comms at all yet (we also have
the individual commits if we get really desperate). Do a release with the
current state as whatever version you want too though

**Comment by znichollscr** [comment]
https://github.com/PCMDI/input4MIPs_CVs/releases/tag/v6.6.1
