### ISSUE TITLE
Tweaks to source_id and data registration formats

### ISSUE THREAD

**Issue by durack1** [PCMDI/input4MIPs_CVs#38]
Working with @znichollscr, we plan to implement a number of updates to streamline the capture of information from the dataset-level (defined by a source_id registration) and file-level (contained as global attributes/metadata in a single file). I will capture recommended changes below. Lose existing `|dataProviderFile` entry altogether.

|  | lose | convert/move | add |
| -- | -- | -- | -- |
| core | `_status`, `nominal_resolution` | convert to list: `frequency`, `grid_label`, `realm`, `target_mip` | |
| dataProviderExtra | | | |
| esgfIndex | | | `_status` |

To file-level, required global_attributes are: `activity_id`, `tracking_id`, `nominal_resolution` (remove `institution`, `table_id`)

For reference this is how a registration looks currently
https://github.com/PCMDI/input4MIPs_CVs/blob/07653ab34adb2fd52798add18aa6e17bdca8b1a1/input4MIPs_source_id.json#L1132-L1171

Will need to add to repo CV list, `input4MIPs_regions.json` following the CF standard region list ([here](https://cfconventions.org/Data/standardized-region-list/standardized-region-list.html)) and converted to JSON in the obs4MIP-cmor-tables repo ([here](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/obs4MIPs_region.json)). As work continues to be finalized upstream in the `mip-cmor-tables` the reproduction of these CVs in this repo could be removed, rather deferring to the upstream sources as the definitive record

**Comment by durack1** [comment]
@znichollscr I also may not have mentioned that I have a couple of reusable functions defined in [`input4MIPsFuncs.py`](https://github.com/PCMDI/input4MIPs-cmor-tables/blob/master/src/input4MIPsFuncs.py), the `checkTrackingId` function might be a useful one in particular

**Comment by znichollscr** [comment]
Thanks Paul! I'll submit a PR tomorrow with my proposal for how this could
work.

**Comment by znichollscr** [comment]
See #39

**Comment by durack1** [comment]
It seems this is now redundant, so closing
