### ISSUE TITLE
Register land use change source_id

### ISSUE THREAD

**Issue by durack1** [PCMDI/input4MIPs_CVs#51]
We need to register a new source_id for the expected land use change dataset. This will be another contribution from the existing institution_id [`UofMD`](https://github.com/PCMDI/mip-cmor-tables/blob/main/MIP_institutions.json#L1442-L1467).

The recommendation was for `UofMD-landState-3-0`, following the previous CMIP6 contributions of `UofMD-landState- 2-1-h`, `UofMD-landState-high-2-1-h`, and `UofMD-landState-low-2-1-h`.

Will need to circle with Louise et al to make sure this and additional registered information can be captured

**Comment by znichollscr** [comment]
Suggestion (same idea as #42)

```
    "UofMD-landState-3-0":{
        "contact":"lchini@umd.edu",
        "further_info_url":"www.tbd.invalid",
        "institution_id":"UofMD",
        "license_id":"CC BY 4.0",
        "mip_era":"CMIP6Plus",
        "source_version":"3.0"
    }
```

**Comment by lchini** [comment]
There will be 3 files as part of the land-use forcing: one for land-use states, one for land-use transitions, and one for land-use management. So we'll need 3 different source IDs. I suggest UofMD-landUseStates-3-0, UofMD-landUseTransitions-3-0, UofMD-landUseManagement-3-0. I will check-in with George Hurtt about these names as well.

**Comment by znichollscr** [comment]
> There will be 3 files as part of the land-use forcing: one for land-use states, one for land-use transitions, and one for land-use management. So we'll need 3 different source IDs

You can just use one source ID and have a different filename for each. E.g. one file would have the variable name, "multiple-land-use-transitions", one could have, "multiple-land-use-states" and one could have, "multiple-land-use-management". That feels like it would be much easier to keep track of to me...

**Comment by znichollscr** [comment]
There's also a proposal to make the DRS able to handle e.g. high/low variants better, see https://github.com/PCMDI/input4MIPs_CVs/discussions/64

**Comment by durack1** [comment]
> There will be 3 files as part of the land-use forcing: one for land-use states, one for land-use transitions, and one for land-use management. So we'll need 3 different source IDs. I suggest UofMD-landUseStates-3-0, UofMD-landUseTransitions-3-0, UofMD-landUseManagement-3-0. I will check-in with George Hurtt about these names as well.

@lchini just circling around on this. The `source_id` is a generic identifier for your dataset, and by "dataset" I mean multiple files that are self-consistent, e.g. historical period. For CMIP6, targeting the historical period, we had `UofMD-landState-2-1-h`, `UofMD-landState-high-2-1-h`, and `UofMD-landState-low-2-1-h`, and each had the 5 files as below
![Screenshot 2024-08-14 at 5 55 58 AM](https://github.com/user-attachments/assets/3a8b25e9-65c7-47b1-8719-b92d7278ef37)

So this time around, how about we start with a single `source_id` = `UofMD-landState-3-0` and then add to this if you decide to go the same high/low path as CMIP6, and then obviously also defining unique id's for the Scenarios, e.g. `UofMD-landState-MAGPIE-ssp585-2-1-f`.

I hope this makes sense?

**Comment by znichollscr** [comment]
Pulling a couple of questions and answers from an email thread into here so we can find them again later.

From Louise:

> ...we have gotten the V0 of the land-use data finished, I'm ready to start uploading files and have been reading through the documentation that Zeb provided. 

> ...I am not exactly sure how I register that source ID though. Do I just edit the file: input4MIPs_CVs/CVs/input4MIPs_source_id.json  to add the lines for the source ID?

Yep. I've created a pull request to do that (https://github.com/PCMDI/input4MIPs_CVs/pull/121), feel free to comment with any changes.

> ...I also noticed that some of the other datasets have multiple entries within that file - do I need multiple entries for the land-use data as well?

No, to start with just do one. If we need to make further releases (because we find bugs, you want to update etc.) then we add new source IDs so we can make clear the difference between versions. (The exception is CEDS data, but they're a special case. We had a long conversation about whether this was a good idea or not, and decided to try it and see in the end. The full conversation is here if you're interested: https://github.com/PCMDI/input4MIPs_CVs/issues/55, with this comment being my reason for only having a single source ID https://github.com/PCMDI/input4MIPs_CVs/issues/55#issuecomment-2311588145.)
