### ISSUE TITLE
Tweaks to sync across contributions

### ISSUE THREAD

**Issue by durack1** [PCMDI/input4MIPs_CVs#52]
- [x] `pollESGF.py` needs to point output from `./` to `../DatasetsDatabase/input-data/`
- [x] catch extra `/` in HTML links off README.md
- [x] correct sublist indenting in README.md

**Comment by znichollscr** [comment]
> * cleanup redundant files in `src/`

I think `src` is now empty in main, so might just be untracked stuff there on your local machine? (https://github.com/PCMDI/input4MIPs_CVs)
