### ISSUE TITLE
target_mip "long name"

### ISSUE THREAD

**Issue by taylor13** [PCMDI/input4MIPs_CVs#58]
I wonder if in the target_MIP CV "long_name" should be replaced by "full_name" or something else.  In the CF coventions the 
long_name attribute is attached to a *variable*, not as a expansion of an abbreviation.  This could lead to some confusion (perhaps not too much, admittedly, but I think it's best to not mix descriptor names for different purposes).

**Comment by znichollscr** [comment]
Sure. Could easily switch to anything as this value isn't used anywhere right now. "description" or "full_name" or "full_title" all seem fine to me

**Comment by taylor13** [comment]
Of those 3 options, I'd vote for "full_name" which seems a bit more specific than "full_title" or "description", but I'm 1 of ? votes.

**Comment by znichollscr** [comment]
> I'm 1 of ? votes

My current guess: 1 of 3. I abstain. So I think the only other person is @durack1  ?

**Comment by durack1** [comment]
full_name works for me - and agreed, trying not to reuse nomenclature when there are different meanings across elements makes far more sense to me
