### ISSUE TITLE
Consistent repo versioning

### ISSUE THREAD

**Issue by durack1** [PCMDI/input4MIPs_CVs#59]
We want to label the version of the repo consistently and clearly, so the following will need to be updated each time a release is minted
- [ ] README.md
- [ ] CITATION.cff
- [ ] All `docs/*.html` files
- [ ] Repo itself

Note to self, there is some code in https://github.com/PCMDI/input4MIPs_CVs/commit/07653ab34adb2fd52798add18aa6e17bdca8b1a1 that was lost but could be recovered which solves the README.md and CITATION.cff updates. The HTML files are currently written using a script, which takes the version as an argument, so that's also close to being implemented

**Comment by znichollscr** [comment]
Notes on the solution in #71:

Everything is fine, except `CITATION.cff`. There's a circular dependency on having the version in there. You need the Zenodo URL to write the `CITATION.cff` file, and you need the repo state (including `CITATION.cff`) to create the Zenodo URL. I've broken this circularity by making `CITATION.cff` point at the Zenodo 'all versions' URL and then telling people to use the more specific version DOI if they need to cite a specific version. I think that should be fine.

**Comment by durack1** [comment]
@znichollscr you can use the persistent DOI: [10.5281/zenodo.12629796](https://zenodo.org/doi/10.5281/zenodo.12629796), this isn't tied to the version, but rather is a "master" DOI that always points to the latest - voila

**Comment by znichollscr** [comment]
Yep cool I think that's what I've done, I just didn't explain it very well. See the current state of the citation file here: https://github.com/PCMDI/input4MIPs_CVs/blob/main/CITATION.cff
