### ISSUE TITLE
Create CMOR input file

### ISSUE THREAD

**Issue by znichollscr** [PCMDI/input4MIPs_CVs#60]
To write files with CMOR, you need a specific input file. It's basically a CMOR table as far as I understand.

We used to package that in this repo, but it has been removed in the reshuffle.

To close this issue:

- [ ] define the required file
- [ ] work out what is required to make that table
- [ ] add back in generation of a CMOR-compatible file (ideally auto-generated with each PR)

x-ref: https://github.com/PCMDI/input4MIPs_CVs/pull/56#issuecomment-2257143968

**Comment by znichollscr** [comment]
@durack1 do you have a link to the kind of file needed/the schema we need to match? Once we have that, I think it should be relatively straight-forward to figure out the rest...

**Comment by durack1** [comment]
@znichollscr this is already captured in https://github.com/PCMDI/input4MIPs_CVs/issues/45

**Comment by znichollscr** [comment]
Great thank you.

Closing in favour of #45.
