### ISSUE TITLE
CR-CMIP-0-3-0

### ISSUE THREAD

**Issue by znichollscr** [PCMDI/input4MIPs_CVs#67]
@durack1 the files for CR-CMIP-0-3-0 are in `/incoming/cr-cmip-0-3-0` on the FTP server and can be queued for publication 🚀

**Comment by durack1** [comment]
@znichollscr files are down and @sashakames has this in his queue for first thing next week! Woo hoo!

**Comment by znichollscr** [comment]
Bug were found in the initial uploads:

- creation date was wrong, fix here (https://github.com/climate-resource/input4mips_validation/pull/60)
- turns out I had the variable handling incorrect
    - current fix: only use variable names that don't have hyphens or underscores in the name
    - question for @durack1. Is the answer for variables with hyphens/underscores the following: in the filename, hyphens only; in the variable ID, match the filename i.e. hyphens only; for the standard name, do whatever https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html shows; for the long name, do whatever you want

Next upload is now on the FTP server so we're back in the publishing queue I think
