### ISSUE TITLE
Automate scrape from ESGF

### ISSUE THREAD

**Issue by znichollscr** [PCMDI/input4MIPs_CVs#69]
At the moment, we manually scrape/poll the ESGF to create our `esgf.json` file. It would be better if this process were automated. That should be possible. The only issue right now is that the API which is hit is not public, so we'd have to work out a workaround. Two possible options: a) whitelist some known GitHub CI API (feels wrong to me though, mainly for security reasons) b) run the script on nimbus, and automatically create PRs into this repository from nimbus using the [GitHub CLI](https://cli.github.com/manual/gh) (this feels like the right solution to me, and would also be pretty easy I think given we already use the GitHub CLI in our GitHub actions).

**Comment by durack1** [comment]
First step cron this, and make available on nimbus

**Comment by durack1** [comment]
@znichollscr anywhere that nimbus can see that you'd recommend this `esgf.json` is dropped? Just setting up the crontab now

**Comment by znichollscr** [comment]
Somewhere that's read only. Other than that, happy with wherever!

**Comment by durack1** [comment]
At the moment this is writing into the repo, which is unique for each user, rather than being in a shared location - e.g. /p/user_pub/work/input4MIPs/ - I think that is the best location, if I have write perms..

**Comment by durack1** [comment]
I think `esgf.json` -> `esgf-input4MIPs.json` works for me..

**Comment by znichollscr** [comment]
All looks good to me.

> At the moment this is writing into the repo, which is unique for each user, rather than being in a shared location

Just to be clear here. We are essentially taking a snapshot of this file each time we commit. So it will be different in different commits, but that's ok, that's the point.

So we should have a shared location on nimbus. But, in this repo, the value of that file could vary commit by commit (which is expected).

**Comment by durack1** [comment]
I'm wondering how we get this back into the repo, as this is part of the whole CV inputs now.. I could commit this to the repo as part of the cron (assuming something has changed), but would want to do this carefully just to make sure we don't create ourselves a problem if the index returns weird results.. Or is offline, etc

**Comment by durack1** [comment]
> Just to be clear here. We are essentially taking a snapshot of this file each time we commit. So it will be different in different commits, but that's ok, that's the point.

Exactly

> So we should have a shared location on nimbus. But, in this repo, the value of that file could vary commit by commit (which is expected).

Nimbus sees the `/p` mount (it's what the nimbus:input4MIPs.ipynb is scanning), so you can also see /p/user_pub/work/input4MIPs/ as can everyone on nimbus

**Comment by durack1** [comment]
@znichollscr just noting, this is now live on nimbus:/p/user_pub/work/input4MIPs/esgf-input4MIPs.json - every 6hrs daily, I'll watch this over the next days to make sure it's working seamlessly

**Comment by znichollscr** [comment]
Ok great. We can work on auto-generating PRs etc. from that!
