### ISSUE TITLE
GitHub pages

### ISSUE THREAD

**Issue by znichollscr** [PCMDI/input4MIPs_CVs#75]
There is some sort of GitHub action going on, that generates a GitHub pages site based on main. See https://pcmdi.github.io/input4MIPs_CVs/

I'm not really sure what this is doing, but I think switching to using mkdocs with GitHub pages is the much more modern solution: https://www.mkdocs.org/user-guide/deploying-your-docs/#github-pages

@durack1 do you know anything about this was set up? Is it just a placeholder or is it performing some key function?

**Comment by durack1** [comment]
Yep, this is just the default GH Pages instance - see https://github.com/PCMDI/input4MIPs_CVs/settings/pages. Keep it as simple as possible is always my preference

**Comment by znichollscr** [comment]
> Keep it as simple as possible is always my preference

Can do. Just running `mkdocs gh-deploy` will be pretty simple

**Comment by durack1** [comment]
This way GH pages works is for each merged commit, the pages are regenerated - no additional step required. If we can batch `mkdocs` into a merge action then we're at the same point as GH Pages

**Comment by znichollscr** [comment]
Is there more than one page on the GH page? At the moment, all I see is the README rendered as a web page, which doesn't seem that helpful, but maybe I am missing something?

**Comment by durack1** [comment]
When I had this configured, it also published the `docs/*html` contents, which was already in HTML (not markdown) so didn't have very much to do - you now have a couple of HTML files in `docs/` so not sure where this is at, what it is doing

**Comment by znichollscr** [comment]
Closing, replaced by more clear issues #86 and #87
