### ISSUE TITLE
SOLARIS-HEPPA-4-3

### ISSUE THREAD

**Issue by znichollscr** [PCMDI/input4MIPs_CVs#82]
Issue for tracking publication of the SOLARIS-HEPPA-4-3 dataset.

At present, the published files with have the filename according to the DRS. This means they will differ from the original filename as published by the SOLARIS team. This isn't ideal, but in the interests of getting data out (particularly while https://github.com/PCMDI/input4MIPs_CVs/discussions/64 is ongoing), we will go with this and see what feedback we get from modelling teams, then improve in the next round.

cc @durack1 @st-bender @berndfunke

**Comment by durack1** [comment]
These files are now live - see [here](https://aims2.llnl.gov/search?project=input4MIPs&activeFacets=%7B%22mip_era%22%3A%22CMIP6Plus%22%2C%22source_id%22%3A%22SOLARIS-HEPPA-CMIP-4-3%22%7D).

@znichollscr the `creation_date` format is another tweak we need to add to the next round (it didn't conform to the format, so was removed), in addition to the #64 discussion in parallel.

@berndfunke - direct links to files are below

| frequency | filename | URL |
| -- | -- | -- |
| day | multiple_input4MIPs_solar_CMIP_SOLARIS-HEPPA-CMIP-4-3_gn_18500101-20231231.nc | [link](https://esgf-data2.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6Plus/CMIP/SOLARIS-HEPPA/SOLARIS-HEPPA-CMIP-4-3/atmos/day/multiple/gn/v20240730/multiple_input4MIPs_solar_CMIP_SOLARIS-HEPPA-CMIP-4-3_gn_18500101-20231231.nc) |
| fx | multiple_input4MIPs_solar_CMIP_SOLARIS-HEPPA-CMIP-4-3_gn.nc | [link](https://esgf-data2.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6Plus/CMIP/SOLARIS-HEPPA/SOLARIS-HEPPA-CMIP-4-3/atmos/fx/multiple/gn/v20240730/multiple_input4MIPs_solar_CMIP_SOLARIS-HEPPA-CMIP-4-3_gn.nc) |
| mon | multiple_input4MIPs_solar_CMIP_SOLARIS-HEPPA-CMIP-4-3_gn_185001-202312.nc | [link](https://esgf-data2.llnl.gov/thredds/fileServer/user_pub_work/input4MIPs/CMIP6Plus/CMIP/SOLARIS-HEPPA/SOLARIS-HEPPA-CMIP-4-3/atmos/mon/multiple/gn/v20240730/multiple_input4MIPs_solar_CMIP_SOLARIS-HEPPA-CMIP-4-3_gn_185001-202312.nc) |

**Comment by znichollscr** [comment]
> @znichollscr the `creation_date` format is another tweak we need to add to the next round (it didn't conform to the format, so was removed), in addition to the #64 discussion in parallel.

Cool this one is my bad! x-ref #66

**Comment by st-bender** [comment]
> These files are now live - see [here](https://aims2.llnl.gov/search?project=input4MIPs&activeFacets=%7B%22mip_era%22%3A%22CMIP6Plus%22%2C%22source_id%22%3A%22SOLARIS-HEPPA-CMIP-4-3%22%7D).
> 
> @znichollscr the `creation_date` format is another tweak we need to add to the next round (it didn't conform to the format, so was removed), in addition to the #64 discussion in parallel.

What is the correct format? I used the same as for CMIP6.

**Comment by znichollscr** [comment]
"YYYY-mm-ddTHH:MM:SSZ". It was my bad and something I broke in the re-write. See #66.

**Comment by st-bender** [comment]
> "YYYY-mm-ddTHH:MM:SSZ". It was my bad and something I broke in the re-write. See #66.

That's how I prepared the files, so nothing to do from our side.

**Comment by durack1** [comment]
> That's how I prepared the files, so nothing to do from our side.

@st-bender agreed, and a reason where possible that we should give data providers feedback to resolve the problems upstream so it's not a problem going forward (or we introduce problems downstream). It turns out this `creation_date` issue is a minor one, and so no major issues that would affect file/data use by any downstream data user.

As @znichollscr notes, we'll catch this next round!

**Comment by st-bender** [comment]
> > That's how I prepared the files, so nothing to do from our side.
> 
> @st-bender agreed, and a reason where possible that we should give data providers feedback to resolve the problems upstream so it's not a problem going forward (or we introduce problems downstream). It turns out this `creation_date` issue is a minor one, and so no major issues that would affect file/data use by any downstream data user.
> 
> As @znichollscr notes, we'll catch this next round!

I am just confused that it was made an issue at all. The files have been written that way for the current round so there is nothing to "catch" for next round?

**Comment by znichollscr** [comment]
> I am just confused that it was made an issue at all. The files have been written that way for the current round so there is nothing to "catch" for next round?

As I said [here](https://github.com/PCMDI/input4MIPs_CVs/issues/82#issuecomment-2288682805), it was my bad. When I re-wrote your files with a different name, I also updated the creation date and tracking ID (because they're different files, so should have different IDs). There was a bug in the tool I was using for this (now resolved, see https://github.com/climate-resource/input4mips_validation/pull/60), hence the creation date written by me was incorrect. As I said, my fault (one of many bugs we'll squash as we go through making a clean dataset for CMIP7), nothing for you to worry about.

**Comment by st-bender** [comment]
> > I am just confused that it was made an issue at all. The files have been written that way for the current round so there is nothing to "catch" for next round?
> 
> As I said [here](https://github.com/PCMDI/input4MIPs_CVs/issues/82#issuecomment-2288682805), it was my bad.

Thanks, I guess I missed that and got confused.

> When I re-wrote your files with a different name, I also updated the creation date and tracking ID (because they're different files, so should have different IDs).

Ok, is there any way for the user to know which file to use?
Essentially, the data are the same, only the metadata differ slightly so they might get confused with the different `tracking_id`s. Should they rely on the `source_id` then?

> There was a bug in the tool I was using for this (now resolved, see [climate-resource/input4mips_validation#60](https://github.com/climate-resource/input4mips_validation/pull/60)), hence the creation date written by me was incorrect.

I had a short look, using `strftime()` that way might work, but then one should also take care that the timestamp really is in `utc` and not in a local time zone. Python's `datetime.datetime` can be both tz-aware and tz-naive. Might not matter much in practice but without proper conversion it could happen that an older file from Europe or Asia has a more recent timestamp than a younger file from the US. One way would be to check the `.tzinfo` attribute (works for pandas and datetime). If it is `None`, assume it is utc, if not, `.tz_convert("utc")` can be used before `.strftime()`.

**Comment by durack1** [comment]
> Ok, is there any way for the user to know which file to use?

@st-bender we have talked about removing the duplicate file downloads, to remove this confusion. Centralizing authoritative versions of data/files in ESGF (see [here](https://github.com/PCMDI/input4MIPs_CVs/issues/66#issuecomment-2266195437)). The confusion here was @znichollscr was being helpful, fixing a little metadata issue (and inserting another :blush:), and that was likely because I did a poor job of communicating the formats - we're trying!

On this topic, let me know if there's any additional info etc you guys need?

> one should also take care that the timestamp really is in `utc` and not in a local time zone

And totally agree - along with also making sure that the local daylight time is also correct. Having said all that, the creation_date attribute is not mission critical, so if we have an hour, or hours wrong it's not going to effect any CMIP7 model simulations down the line - but it would be great to get this right

**Comment by st-bender** [comment]
> > Ok, is there any way for the user to know which file to use?
> 
> @st-bender we have talked about removing the duplicate file downloads, to remove this confusion. Centralizing authoritative versions of data/files in ESGF (see [here](https://github.com/PCMDI/input4MIPs_CVs/issues/66#issuecomment-2266195437)).

Yes I understand. We can sort this out when everybody is back from vacation. Right now it is difficult to find out if there are people that rely on the file name format. Will probably fine, though.
 
> On this topic, let me know if there's any additional info etc you guys need?

Not from the top of my head. So far I think we are good since we sorted out the attributes and the format.
