### ISSUE TITLE
Capture version deprecation information in CVs

### ISSUE THREAD

**Issue by durack1** [PCMDI/input4MIPs_CVs#90]
We have had a single case of the SOLARIS-HEPPA-CMIP-4-2 [retracted](https://aims2.llnl.gov/search?project=input4MIPs&versionType=all&activeFacets=%7B%22frequency%22%3A%22mon%22%2C%22mip_era%22%3A%22CMIP6Plus%22%2C%22source_id%22%3A%22SOLARIS-HEPPA-CMIP-4-2%22%7D) dataset which was promptly replaced with the replaced by SOLARIS-HEPPA-CMIP-4-3. In an associated issue, there is the note the problem was [“encountered an issue with the proton ionization data in v4.2” 29 Jul 2024](https://github.com/PCMDI/input4MIPs_CVs/issues/17#issuecomment-2255378927), but this is not prominently available.

It would be ideal to capture a meaningful description of the problem and how it is solved so that a modeling group can ascertain whether they need to pay attention to the data correction or proceed with their existing version. For this v4.2 -> v4.3 dataset update, presumably, most modeling groups would be concerned with wrong data (@vnaik60, do you use the proton ionization data for simulations?)., but in the case that there was a metadata inconsistency, then such a problem would be unlikely to require a data switchout.

ping @znichollscr @vnaik60

**Comment by znichollscr** [comment]
Hi both, I'd suggest capturing this in the following way:

1. we add a post-publication comment to the SOLARIS-HEPPA-4-2 data which explains why it was deprecated. That is added in #91 
2. we add a source ID level view to our docs, so it's easier for people to see what is going on at a higher level than what is provided by the files and dataset views (which have other benefits, so we should keep them, but no single view will serve all purposes). That is added in #92 

The end result is a view like the following (note the search field in the top-right), which I think looks pretty clear. If you want to play around with this view yourself, [the preview is here](https://refined-github-html-preview.kidonng.workers.dev/PCMDI/input4MIPs_CVs/raw/add-source-id-view/docs/input4MIPs_source-id_CMIP6Plus.html)

<img width="1436" alt="Screenshot 2024-08-16 at 7 45 25 am" src="https://github.com/user-attachments/assets/0789c513-b877-4ded-bea8-b7344d7b3a81">

**Comment by vnaik60** [comment]
Excellent point @durack1! It would be important to keep track of the updates and reasons for deprecation of the previous version of the data just as was done manually in i[nput4MIPs summary doc](https://docs.google.com/document/d/1pU9IiJvPJwRvIgVaSDdJ4O0Jeorv_2ekEtted34K9cA/edit#heading=h.kbcgohrf04fo). 
No, we dont use the proton ionization data for simulations. 

@znichollscr this seems like a sensible approach to me, though, @durack1 would have more thoughts. By the way, did you lose the "latest" column in this version?

**Comment by durack1** [comment]
@znichollscr you are a wizard!

A couple of nits
- for the abandoned datasets, as the SOLARIS-HEPPA v4.1 was made available, but not through ESGF we need to be careful with details so how about "registered but never published to ESGF". This will also be the case with some of the alpha-prototype data that Tom has been handing about. As CR-CMIP-0-2-0 never saw the light of day (no external party ever got their hands on it, no?) this comment is accurate
- The the "latest" point of @vnaik60. This is buried in the "publication_status" key, with "published" = latest, "retracted" = not latest, "registered" = we know about it and it's imminent, and "abandoned" - I think this is perfect, @vnaik60 is that ok with you?

Otherwise this looks like just the ticket.

I was hoping we could add the "source_id view, datasets view, files view" links across the HTML header - much like we have with the links on the https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html page(s). If you have the bandwidth, then I think that is all, and solves all our discussed HTML ponderings

**Comment by durack1** [comment]
Resolved by #91
