### ISSUE TITLE
Deploying website for each version

### ISSUE THREAD

**Issue by znichollscr** [PCMDI/input4MIPs_CVs#96]
If you do builds of your website with e.g. [ReadTheDocs](https://about.readthedocs.com/?ref=readthedocs.com), you can make it possible for users to look at the docs at different versions of your package/deployment. For example, with input4MIPs validation, users can look at:

- [latest](https://input4mips-validation.readthedocs.io/en/latest/) i.e. the latest commit in main
- [stable](https://input4mips-validation.readthedocs.io/en/stable/) i.e. the latest tagged commit
- [v0.10.2](https://input4mips-validation.readthedocs.io/en/v0.10.2/), a specific tag
- [v0.11.3](https://input4mips-validation.readthedocs.io/en/v0.11.3/), a different specific tag

etc.

Unfortunately, with GitHub pages, this doesn't appear to be possible. [GitHub pages just always serves the data in the gh-pages branch](https://stackoverflow.com/a/37145848).

It would add more complexity (but not much, this is how we do all our docs at CR, including input4mips validation), but would this extra feature be useful? It would mean that people could easily see the state of the database/CVs at an earlier point in time, should they ever need to look at how things were at a specific commit rather than always just seeing the latest commit in main on the deployed docs site.

@durack1 interested in your thoughts here

**Comment by durack1** [comment]
To be honest I really like the idea of this, BUT, the maintenance of this is my only concern. The keep it simple st*pid is a good way to ascertain this - BUT, I really do like the ability of being able to go back in time to a snapshot trivially, I always have trouble doing this in the github commit history..

**Comment by znichollscr** [comment]
I'll make an MR and we can discuss whether we go for it or not.
